# Generated by Django 5.2.8 on 2025-12-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_contact_id_alter_fitnessprofile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessprofile',
            name='bmi',
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='interested_program',
            field=models.CharField(default='zumba', max_length=100),
            preserve_default=False,
        ),
    ]
