# Generated by Django 6.0 on 2025-12-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_contact_id_alter_fitnessprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
