# Generated by Django 6.0 on 2025-12-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_consultation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
